repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
    -   id: mypy
        args: ["--config-file=mypy.ini"]
        additional_dependencies: [
          'pydantic',
          'litestar',
        ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [--config=ruff.toml]
      - id: ruff-format
        args: [--config=ruff.toml]